import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import test from 'node:test';

interface ReleasePleaseConfig {
  packages: {
    '.': {
      component: string;
      'package-name': string;
    };
  };
}

interface PackageJson {
  name: string;
  displayName: string;
}

function readJson<T>(path: string): T {
  return JSON.parse(readFileSync(join(process.cwd(), path), 'utf8')) as T;
}

function readPublishWorkflow(): string {
  return readFileSync(join(process.cwd(), '.github/workflows/publish.yml'), 'utf8');
}

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

test('publish workflow accepts release tags generated by Release Please', () => {
  const packageJson = readJson<PackageJson>('package.json');
  const releaseConfig = readJson<ReleasePleaseConfig>('release-please-config.json').packages['.'];
  const publishWorkflow = readPublishWorkflow();
  const component = releaseConfig.component;
  const tagPrefix = `${component}-v`;

  assert.equal(releaseConfig['package-name'], packageJson.name);
  assert.equal(component, packageJson.name);
  assert.match(
    publishWorkflow,
    new RegExp(`startsWith\\((github\\.event\\.release\\.tag_name \\|\\| inputs\\.release_tag), '${escapeRegExp(tagPrefix)}'\\)`)
  );
  assert.match(
    publishWorkflow,
    new RegExp(`RELEASE_TAG: \\$\\{\\{ (github\\.event\\.release\\.tag_name \\|\\| inputs\\.release_tag) \\}\\}`)
  );
  assert.match(publishWorkflow, new RegExp(`RELEASE_TAG#${escapeRegExp(tagPrefix)}`));
  assert.match(publishWorkflow, new RegExp(`${escapeRegExp(component)}-\\$\\{\\{ steps\\.pkg\\.outputs\\.version \\}\\}\\.vsix`));
  assert.match(publishWorkflow, /comment-doc-lens-v/);
  assert.doesNotMatch(publishWorkflow, new RegExp(['comment', 'lens-v'].join('-')));
});

test('publish workflow can be rerun manually for an existing release tag', () => {
  const publishWorkflow = readPublishWorkflow();

  assert.match(publishWorkflow, /workflow_dispatch:/);
  assert.match(publishWorkflow, /release_tag:/);
  assert.match(publishWorkflow, /github\.event\.release\.tag_name \|\| inputs\.release_tag/);
});

test('marketplace display-name conflicts fail instead of rewriting metadata', () => {
  const packageJson = readJson<PackageJson>('package.json');
  const publishWorkflow = readPublishWorkflow();
  const rejectedWorkaroundDisplayName = ['Comment', 'Lens Inline Docs'].join(' ');

  assert.equal(packageJson.displayName, 'Comment Doc Lens');
  assert.match(publishWorkflow, /npx @vscode\/vsce publish --skip-duplicate --packagePath/);
  assert.doesNotMatch(publishWorkflow, /displayName/i);
  assert.doesNotMatch(publishWorkflow, new RegExp(escapeRegExp(rejectedWorkaroundDisplayName)));
  assert.doesNotMatch(publishWorkflow, /\bgit\s+(commit|push)\b/);
  assert.doesNotMatch(publishWorkflow, /\b(jq|sed|perl|node)\b[^\n]*displayName/i);
});
